---
- name: Install ansible for lxc
  hosts: local
  connection: local
  become: True
  gather_facts: False
  tags: provisionLxc
  roles:
    - provisionLxc

- name: Initial instance for lxc
  hosts: lxc-launch
  become: True
  gather_facts: False
  tags: initialLxcServer
  roles:
    - initialServer
