---
- name: update apt packages
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: installing packages
  apt: "name={{ item }} state=installed"
  with_items:
    - python2.7-minimal
    - python-boto
    - vim
    - unzip
    - curl
    - htop
    - language-pack-en-base

- name: Create the file /etc/apt/sources.list.d/pgdg.list, and add a line for the repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main
    state: present

- name: initialize keys postgresql
  apt_key: >
    url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state=present

- name: installing postgresql
  apt: >
    name=postgresql-10
    state=present
    force=yes
  notify:
    - Start/Restart PostgreSQL and Start @ Boot
