---
- name: Download percona_package
  get_url:
    url="http://repo.percona.com/apt/percona-release_0.1-6.trusty_all.deb"
    dest="/tmp/percona-release_0.1-6.trusty_all.deb"

- name: Install percona_package
  apt: >
    deb="/tmp/percona-release_0.1-6.trusty_all.deb"

- name: update apt packages
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: installing packages
  apt: "name={{ item }} state=installed"
  with_items:
    - python2.7-minimal
    - python-boto
    - vim
    - unzip
    - curl
    - htop
    - language-pack-en-base
    - python-mysqldb

- name: Check if Percona is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if Percona is not yet installed.
  apt: update_cache=yes
  when: mysql_installed.stat.exists == false

- name: Ensure Percona packages are installed.
  apt: "name={{ item }} state=installed"
  with_items:
    - percona-xtradb-cluster-full-57
    - libmysqlclient18
  when: mysql_installed.stat.exists == false

# - name: restart mysql service
#   action: service name=mysql state=restarted enabled=true
