---
- name: update apt packages
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: installing packages
  apt: "name={{ item }} state=installed"
  with_items:
    - python-boto
    - vim
    - unzip
    - curl
    - htop
    - language-pack-en-base
    - python-mysqldb

- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes
  when: mysql_installed.stat.exists == false

- name: Ensure MySQL packages are installed.
  apt: "name={{ item }} state=installed"
  with_items:
    - mysql-common
    - mysql-server
    - libmysqlclient-dev
  when: mysql_installed.stat.exists == false

- name: Deploy config mysql for master
  copy: >
    src=files/mysql/mysql_master_cnf
    dest=/etc/mysql/my.cnf
    mode=0644
  notify: Start/Restart mysqld and Start @ Boot

- name: Deploy .my.cnf for root
  template: >
    src=templates/mysql/my_cnf
    dest=~/.my.cnf
  with_items: "{{ active_apps }}"
