---
- name: generate Instance for staging1 in {{ region }}
  ec2:
    wait: yes
    key_name: "{{ keypair }}"
    group_id: "{{ staging_firewall.group_id }}"
    region: "{{ region }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image_ubuntu_1404 }}"
    instance_tags:
      Name: "{{ security_group }}"
    # volumes:
    #   - device_name: /dev/sda1
    #     volume_type: gp2
    #     volume_size: 300
    #     delete_on_termination: true
    #   - device_name: /dev/sdb
    #     volume_type: gp2
    #     volume_size: 80
    #     delete_on_termination: true
  register: launch_staging1

- name: initialing apps for staging1 in {{ region }} - {{ launch_staging1.instances[0].public_ip }}
  add_host:
    hostname: "{{ launch_staging1.instances[0].public_ip }}"
    groupname: staging1-launch

- name: Wait for SSH to come up
  wait_for:
    host: "{{ launch_staging1.instances[0].public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ launch_staging1.instances[0].id }}"
