---
- name: Take SecurityGroups for staging1 down
  ec2_group:
    name: "{{ security_group }}"
    description: an staging1 EC2 group
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    state: "absent"
